prometheus updates

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -15,6 +15,45 @@ services:
       # and restart nginx.  More info in README.
     networks:
       - promnet
+    depends_on:
+      - remote-storage-adapter
+      - influxdb
+      - node-exporter
+
+  remote-storage-adapter:
+    image: gavind/prometheus-remote-storage-adapter:1.0
+    ports:
+      - 9201:9201
+    command: ['-influxdb-url=http://localhost:8086', '-influxdb.database=prometheus', '-influxdb.retention-policy=autogen']
+    network_mode: 'host'
+    depends_on:
+      - influxdb
+
+  influxdb:
+    image: influxdb:1.3.5
+    command: -config /etc/influxdb/influxdb.conf
+    ports:
+      - 8086:8086
+    volumes:
+      - ./influxdata:/var/lib/influxdb
+
+#  pg_prometheus:
+#    image: timescale/pg_prometheus:latest
+#    command: -c synchronous_commit=OFF
+#    container_name: pg_prometheus
+#    healthcheck:
+#      test: ["CMD-SHELL", "pg_isready -U postgres"]
+#      interval: 1s
+#      timeout: 5s
+#      retries: 10
+#
+#  prometheus_postgresql_adapter:
+#    image: timescale/prometheus-postgresql-adapter:latest
+#    ports:
+#      - 9201:9201
+#    depends_on:
+#      - "pg_prometheus"
+#    command: "-pg.host=pg_prometheus -pg.prometheus-log-samples -pg.password=PASSWORD"
 
   # Explore current machine metric for prometheus to scrape.
   node-exporter:
@@ -39,42 +78,42 @@ services:
 #    networks:
 #      - promnet
 
-  app:
-    build: "."
-    restart: "always"
-    ports:
-    - ${APP_PORT:-3000}:3000
-    env_file:
-      - ".env"
-    depends_on:
-    - "db"
-    volumes:
-    - ".:/go/src/github.com/opacity/storage-node"
-    - "./data/badger/prod:/var/lib/badger/prod"
-    - "./data/badger/test:/var/lib/badger/test"
-    working_dir: "/go/src/github.com/opacity/storage-node"
-    command: >
-      bash -c "
-        echo waiting for db...;
-        while ! nc -z db 3306;
-        do
-          sleep 0.5;
-          free -m;
-        done;
-        echo ${DEBUG}
-        go get github.com/codegangsta/gin
-        if [ -z ${DEBUG} ]; then
-          echo \"Starting Storage node in PROD mode\";
-          go build -o ./bin/storage-node && chmod +x ./bin/storage-node;
-          ./bin/storage-node;
-        else
-          echo \"Starting Storage node in DEV mode\";
-          gin run main.go
-        fi
-      "
-    networks:
-      - promnet
-      - dbnet
+#  app:
+#    build: "."
+#    restart: "always"
+#    ports:
+#      - ${APP_PORT:-3000}:3000
+#    env_file:
+#      - ".env"
+#    depends_on:
+#      - "db"
+#    volumes:
+#      - ".:/go/src/github.com/opacity/storage-node"
+#      - "./data/badger/prod:/var/lib/badger/prod"
+#      - "./data/badger/test:/var/lib/badger/test"
+#    working_dir: "/go/src/github.com/opacity/storage-node"
+#    command: >
+#      bash -c "
+#        echo waiting for db...;
+#        while ! nc -z db 3306;
+#        do
+#          sleep 0.5;
+#          free -m;
+#        done;
+#        echo ${DEBUG}
+#        go get github.com/codegangsta/gin
+#        if [ -z ${DEBUG} ]; then
+#          echo \"Starting Storage node in PROD mode\";
+#          go build -o ./bin/storage-node && chmod +x ./bin/storage-node;
+#          ./bin/storage-node;
+#        else
+#          echo \"Starting Storage node in DEV mode\";
+#          gin run main.go
+#        fi
+#      "
+#    networks:
+#      - promnet
+#      - dbnet
 
   db:
     container_name: mysql
